"""
calibrate_hyperplanes.py — Data-Calibrated Entropy-Maximized Hyperplanes (ITQ / PCA)

Implements Pillar 1 of the ER2 architecture:
1. Samples vectors from the corpus or MiniLM embeddings.
2. Centers the data and computes the top 32 principal components (PCA).
3. Executes Iterative Quantization (ITQ, Gong & Lazebnik 2011) to rotate
   the hyperplanes to minimize quantization error ||V - sgn(V * R)||^2.
4. Computes per-bit Shannon entropy and bit balance to guarantee H(b_i) ≈ 1.0.
5. Exports the calibrated orthogonal hyperplanes to src/probe_vectors.h.
"""

import os
import sys
import math
import numpy as np

DIMS = 384
NUM_PROBES = 32
ITQ_ITERATIONS = 50


def train_itq(X: np.ndarray, num_bits: int = 32, max_iter: int = 50) -> np.ndarray:
    """
    Trains Iterative Quantization (ITQ) projection matrix on data matrix X (N x D).
    Returns D x num_bits projection matrix P = W * R.
    """
    N, D = X.shape
    # 1. Zero-center data
    mean = np.mean(X, axis=0)
    X_centered = X - mean

    # 2. PCA to reduce from D to num_bits
    cov = np.dot(X_centered.T, X_centered) / (N - 1)
    eigenvalues, eigenvectors = np.linalg.eigh(cov)
    # Sort descending
    idx = np.argsort(eigenvalues)[::-1]
    eigenvectors = eigenvectors[:, idx]
    W = eigenvectors[:, :num_bits]  # D x num_bits
    V = np.dot(X_centered, W)       # N x num_bits

    # 3. ITQ Rotation: Orthogonal Procrustes optimization
    # Initialize R with random orthogonal matrix via QR decomposition
    np.random.seed(42)
    G = np.random.randn(num_bits, num_bits)
    R, _ = np.linalg.qr(G)

    for i in range(max_iter):
        # Quantize
        VR = np.dot(V, R)
        B = np.where(VR >= 0, 1.0, -1.0)

        # Update R via SVD of B^T * V
        C = np.dot(B.T, V)
        U, S, Vt = np.linalg.svd(C)
        R = np.dot(Vt.T, U.T)

    # Final projection hyperplanes: P = W * R (D x num_bits)
    # Each column of P is one hyperplane vector
    P = np.dot(W, R)
    return P


def export_probe_vectors(P: np.ndarray, out_path: str = "src/probe_vectors.h"):
    """
    Exports the D x NUM_PROBES matrix P as NUM_PROBES x D array in C++ header.
    """
    # P has shape (DIMS, NUM_PROBES). We want PROBE_VECTORS[NUM_PROBES][DIMS].
    probes = P.T  # shape (NUM_PROBES, DIMS)

    # Normalize each hyperplane to unit length
    for i in range(NUM_PROBES):
        norm = np.linalg.norm(probes[i])
        if norm > 1e-9:
            probes[i] /= norm

    with open(out_path, "w") as f:
        f.write("#pragma once\n")
        f.write("// AUTO-GENERATED by scripts/calibrate_hyperplanes.py (ITQ / PCA)\n")
        f.write("// Data-Calibrated Entropy-Maximized Hyperplanes (Pillar 1)\n\n")
        f.write(f"static constexpr int P3_NUM_PROBES = {NUM_PROBES};\n")
        f.write(f"static constexpr int P3_DIMS = {DIMS};\n\n")
        f.write(f"static const float PROBE_VECTORS[{NUM_PROBES}][{DIMS}] = {{\n")
        for i in range(NUM_PROBES):
            f.write(f"    {{ // probe {i}\n")
            vals_per_line = 8
            for j in range(0, DIMS, vals_per_line):
                chunk = probes[i, j:j + vals_per_line]
                line = ", ".join(f"{v:.8f}f" for v in chunk)
                f.write(f"        {line},\n")
            f.write("    },\n")
        f.write("};\n")

    print(f"[*] Successfully exported {NUM_PROBES} calibrated hyperplanes to {out_path}")


def main():
    print("=" * 60)
    print("  BitDB ER2 — ITQ Hyperplane Calibration (Pillar 1)")
    print("=" * 60)

    # Check if we can sample embeddings from chunk_store or generate synthetic MiniLM sample
    sample_vectors = None
    chunk_store_path = "DataStorage/chunk_store.bin"
    
    if os.path.exists(chunk_store_path) and os.path.getsize(chunk_store_path) > 131072:
        print(f"[*] Sampling vectors directly from {chunk_store_path}...")
        vectors = []
        EXTENT_BYTES = 131072
        EXTENT_CAPACITY = 283
        HEADER_BYTES = 512
        STAGE1_BYTES = 14096
        with open(chunk_store_path, "rb") as f:
            while len(vectors) < 5000:
                block_data = f.read(EXTENT_BYTES)
                if len(block_data) < EXTENT_BYTES:
                    break
                rec_count = int.from_bytes(block_data[4:8], byteorder="little")
                emb_bytes = block_data[STAGE1_BYTES:STAGE1_BYTES + (rec_count * DIMS)]
                arr = np.frombuffer(emb_bytes, dtype=np.int8).reshape(rec_count, DIMS)
                for vec in arr:
                    vectors.append(vec.astype(np.float32) / 127.0)
                    if len(vectors) >= 5000:
                        break
        if len(vectors) >= 500:
            sample_vectors = np.array(vectors)
            print(f"[*] Loaded {len(sample_vectors)} real corpus vectors.")

    if sample_vectors is None:
        print("[*] Generating anisotropic Gaussian sample vectors (384-dim)...")
        np.random.seed(42)
        # Simulate anisotropic language embedding manifold (variance on leading components)
        decay = np.exp(-np.arange(DIMS) / 40.0)
        sample_vectors = np.random.randn(5000, DIMS) * decay
        sample_vectors = sample_vectors / np.linalg.norm(sample_vectors, axis=1, keepdims=True)

    print(f"[*] Running Iterative Quantization (ITQ) over {len(sample_vectors)} vectors...")
    P = train_itq(sample_vectors, num_bits=NUM_PROBES, max_iter=ITQ_ITERATIONS)

    # Evaluate bit entropy on sample vectors
    projected = np.dot(sample_vectors, P)
    bits = (projected >= 0).astype(int)
    p1 = np.mean(bits, axis=0)

    entropies = []
    for p in p1:
        p = np.clip(p, 1e-6, 1.0 - 1e-6)
        h = -(p * math.log2(p) + (1.0 - p) * math.log2(1.0 - p))
        entropies.append(h)

    mean_entropy = np.mean(entropies)
    print("\n" + "─" * 40)
    print("  HYPERPLANE CALIBRATION METRICS")
    print("─" * 40)
    print(f"  Mean Bit Entropy : {mean_entropy:.4f} / 1.0000")
    print(f"  Min Bit Balance  : {np.min(p1)*100:.1f}% ones")
    print(f"  Max Bit Balance  : {np.max(p1)*100:.1f}% ones")
    print(f"  Mean Bit Balance : {np.mean(p1)*100:.1f}% ones")
    print("─" * 40)

    export_probe_vectors(P, "src/probe_vectors.h")


if __name__ == "__main__":
    main()
