// ════════════════════════════════════════════════════════════════════════
// HaltonProbes.cpp — Native C++ Space-Filling Halton Probe Generator
// Replaces scripts/gen_probes.py directly in C++.
// ════════════════════════════════════════════════════════════════════════

#include <iostream>
#include <fstream>
#include <vector>
#include <cmath>
#include <string>
#include <iomanip>
#include <filesystem>
#include "PathConfig.h"

using namespace std;
namespace fs = std::filesystem;

static const int PRIMES[32] = {
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29,
    31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
    73, 79, 83, 89, 97, 101, 103, 107, 109, 113,
    127, 131
};

static constexpr int NUM_PROBES = 32;
static constexpr int DIMS = 384;

static double halton(int index, int base) {
    double result = 0.0;
    double denominator = 1.0;
    int n = index + 1;
    while (n > 0) {
        denominator *= base;
        result += (n % base) / denominator;
        n /= base;
    }
    return result;
}

static vector<float> generate_probe_vector(int probe_idx) {
    vector<float> vec(DIMS);
    double sum_sq = 0.0;
    for (int dim = 0; dim < DIMS; ++dim) {
        int prime_idx = (dim + probe_idx * 7) % 32;
        int base = PRIMES[prime_idx];
        double h = halton(probe_idx * DIMS + dim, base);
        float val = static_cast<float>(h * 2.0 - 1.0);
        vec[dim] = val;
        sum_sq += val * val;
    }

    double norm = sqrt(sum_sq);
    if (norm > 1e-9) {
        for (int dim = 0; dim < DIMS; ++dim) {
            vec[dim] = static_cast<float>(vec[dim] / norm);
        }
    }
    return vec;
}

int main() {
    cout << "==================================================\n";
    cout << "  BitDB Native C++ Halton Probe Generator\n";
    cout << "==================================================\n";
    cout << "[*] Generating " << NUM_PROBES << " probe vectors of dimension " << DIMS << "...\n";

    vector<vector<float>> probes(NUM_PROBES);
    for (int i = 0; i < NUM_PROBES; ++i) {
        probes[i] = generate_probe_vector(i);
    }

    fs::path outPath = PathConfig::getProjectRoot() / "src" / "probe_vectors.h";
    ofstream f(outPath.string(), ios::trunc);
    if (!f) {
        cerr << "[!] ERROR: Cannot open output path: " << outPath.string() << "\n";
        return 1;
    }

    f << "#pragma once\n";
    f << "// AUTO-GENERATED by HaltonProbes (C++ native)\n";
    f << "// BitDB Halton Space-Filling Hyperplanes (32 x 384)\n\n";
    f << "static constexpr int P3_NUM_PROBES = " << NUM_PROBES << ";\n";
    f << "static constexpr int P3_DIMS = " << DIMS << ";\n\n";

    f << "static const float CENTROID_VECTOR[" << DIMS << "] = {\n";
    for (int j = 0; j < DIMS; j += 8) {
        f << "        ";
        for (int k = 0; k < 8 && j + k < DIMS; ++k) {
            f << "0.00000000f, ";
        }
        f << "\n";
    }
    f << "};\n\n";

    f << "static const float PROBE_VECTORS[" << NUM_PROBES << "][" << DIMS << "] = {\n";
    for (int i = 0; i < NUM_PROBES; ++i) {
        f << "    { // probe " << i << "\n";
        for (int j = 0; j < DIMS; j += 8) {
            f << "        ";
            for (int k = 0; k < 8 && j + k < DIMS; ++k) {
                f << fixed << setprecision(8) << probes[i][j + k] << "f, ";
            }
            f << "\n";
        }
        f << "    },\n";
    }
    f << "};\n";
    f.close();

    cout << "[*] Successfully generated and wrote: " << outPath.string() << "\n";
    cout << "==================================================\n";
    return 0;
}
