"""
calibrate_hyperplanes.py — Data-Calibrated Entropy-Maximized Hyperplanes (Centroid + PCA)

Implements Centroid + PCA Approach:
1. Samples vectors from the corpus.
2. Computes and saves the centroid.
3. Centers the data and computes the top 32 principal components (PCA).
4. Exports the calibrated centroid and PCA hyperplanes to src/probe_vectors.h.
"""

import os
import sys
import math
import numpy as np

DIMS = 384
NUM_PROBES = 32

def train_pca_centroid(X: np.ndarray, num_bits: int = 32):
    N, D = X.shape
    # 1. Compute Centroid
    centroid = np.mean(X, axis=0)
    X_centered = X - centroid

    # 2. PCA to reduce from D to num_bits
    cov = np.dot(X_centered.T, X_centered) / (N - 1)
    eigenvalues, eigenvectors = np.linalg.eigh(cov)
    
    # Sort descending
    idx = np.argsort(eigenvalues)[::-1]
    eigenvectors = eigenvectors[:, idx]
    P = eigenvectors[:, :num_bits]  # D x num_bits
    
    return centroid, P

def export_pca_probes(centroid: np.ndarray, P: np.ndarray, out_path: str = "src/probe_vectors.h"):
    probes = P.T  # shape (NUM_PROBES, DIMS)

    # Normalize each hyperplane to unit length
    for i in range(NUM_PROBES):
        norm = np.linalg.norm(probes[i])
        if norm > 1e-9:
            probes[i] /= norm

    with open(out_path, "w") as f:
        f.write("#pragma once\n")
        f.write("// AUTO-GENERATED by scripts/calibrate_hyperplanes.py (Centroid + PCA)\n")
        f.write("// Data-Calibrated Hyperplanes\n\n")
        f.write(f"static constexpr int P3_NUM_PROBES = {NUM_PROBES};\n")
        f.write(f"static constexpr int P3_DIMS = {DIMS};\n\n")
        
        # Write Centroid
        f.write(f"static const float CENTROID_VECTOR[{DIMS}] = {{\n")
        vals_per_line = 8
        for j in range(0, DIMS, vals_per_line):
            chunk = centroid[j:j + vals_per_line]
            line = ", ".join(f"{v:.8f}f" for v in chunk)
            f.write(f"        {line},\n")
        f.write("};\n\n")

        # Write Probes
        f.write(f"static const float PROBE_VECTORS[{NUM_PROBES}][{DIMS}] = {{\n")
        for i in range(NUM_PROBES):
            f.write(f"    {{ // probe {i}\n")
            for j in range(0, DIMS, vals_per_line):
                chunk = probes[i, j:j + vals_per_line]
                line = ", ".join(f"{v:.8f}f" for v in chunk)
                f.write(f"        {line},\n")
            f.write("    },\n")
        f.write("};\n")

    print(f"[*] Successfully exported centroid and {NUM_PROBES} calibrated hyperplanes to {out_path}")

def main():
    print("=" * 60)
    print("  BitDB ER2 — Centroid + PCA Hyperplane Calibration")
    print("=" * 60)

    script_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
    project_root = os.path.abspath(os.path.join(script_dir, "..")) if os.path.basename(script_dir) == "scripts" else script_dir
    chunk_store_path = os.path.join(project_root, "DataStorage", "chunk_store.bin")
    
    sample_vectors = None
    if os.path.exists(chunk_store_path) and os.path.getsize(chunk_store_path) > 131072:
        print(f"[*] Reading all corpus vectors directly from {chunk_store_path}...")
        vectors = []
        EXTENT_BYTES = 131072
        STAGE1_BYTES = 14096
        with open(chunk_store_path, "rb") as f:
            while True:
                block_data = f.read(EXTENT_BYTES)
                if len(block_data) < EXTENT_BYTES:
                    break
                rec_count = int.from_bytes(block_data[4:8], byteorder="little")
                emb_bytes = block_data[STAGE1_BYTES:STAGE1_BYTES + (rec_count * DIMS)]
                arr = np.frombuffer(emb_bytes, dtype=np.int8).reshape(rec_count, DIMS)
                for vec in arr:
                    vectors.append(vec.astype(np.float32) / 127.0)
        if len(vectors) >= 500:
            sample_vectors = np.array(vectors)
            print(f"[*] Loaded {len(sample_vectors)} real corpus vectors across all extents.")

    if sample_vectors is None:
        print("[*] Generating anisotropic Gaussian sample vectors (384-dim)...")
        np.random.seed(42)
        decay = np.exp(-np.arange(DIMS) / 40.0)
        sample_vectors = np.random.randn(5000, DIMS) * decay
        sample_vectors = sample_vectors / np.linalg.norm(sample_vectors, axis=1, keepdims=True)

    print(f"[*] Running Centroid + PCA over {len(sample_vectors)} vectors...")
    centroid, P = train_pca_centroid(sample_vectors, num_bits=NUM_PROBES)

    projected = np.dot(sample_vectors - centroid, P)
    bits = (projected >= 0).astype(int)
    p1 = np.mean(bits, axis=0)

    entropies = []
    for p in p1:
        p = np.clip(p, 1e-6, 1.0 - 1e-6)
        h = -(p * math.log2(p) + (1.0 - p) * math.log2(1.0 - p))
        entropies.append(h)

    mean_entropy = np.mean(entropies)
    print("\n" + "-" * 40)
    print("  HYPERPLANE CALIBRATION METRICS")
    print("-" * 40)
    print(f"  Mean Bit Entropy : {mean_entropy:.4f} / 1.0000")
    print(f"  Min Bit Balance  : {np.min(p1)*100:.1f}% ones")
    print(f"  Max Bit Balance  : {np.max(p1)*100:.1f}% ones")
    print(f"  Mean Bit Balance : {np.mean(p1)*100:.1f}% ones")
    script_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
    project_root = os.path.abspath(os.path.join(script_dir, "..")) if os.path.basename(script_dir) == "scripts" else script_dir
    out_path = os.path.join(project_root, "src", "probe_vectors.h")
    export_pca_probes(centroid, P, out_path)

if __name__ == "__main__":
    main()
