"""
gen_probes.py — Generates 32 x 384 probe vectors using a Halton low-discrepancy sequence.

These are NOT random LSH hyperplanes. They are deterministic space-filling vectors
produced from the Halton sequence in 384 dimensions (using first 32 prime bases).
They serve as routing "probe vectors" for Prototype-3's segment-routing scheme.

Run this script once to regenerate src/probe_vectors.h.
"""

import math

PRIMES = [
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29,
    31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
    73, 79, 83, 89, 97, 101, 103, 107, 109, 113,
    127, 131
]

NUM_PROBES = 32
DIMS = 384


def halton(index: int, base: int) -> float:
    """Compute the Halton sequence value at position 'index' for given 'base'."""
    result = 0.0
    denominator = 1.0
    n = index + 1   # 1-indexed so we skip 0
    while n > 0:
        denominator *= base
        result += (n % base) / denominator
        n //= base
    return result


def generate_probe_vector(probe_idx: int) -> list:
    """
    Generate a single 384-dimensional probe vector using Halton sequence.
    Each dimension uses a different prime base, cycling through available primes.
    Values are mapped from [0,1] to [-1,1] then L2-normalized.
    """
    vec = []
    for dim in range(DIMS):
        # Use a different prime for each dimension, cycling. Offset by probe_idx.
        prime_idx = (dim + probe_idx * 7) % len(PRIMES)
        base = PRIMES[prime_idx]
        # Sample at position (probe_idx * DIMS + dim + 1) in the Halton sequence
        h = halton(probe_idx * DIMS + dim, base)
        # Map [0,1] -> [-1, 1]
        vec.append(h * 2.0 - 1.0)

    # L2 normalize
    norm = math.sqrt(sum(v * v for v in vec))
    if norm > 1e-9:
        vec = [v / norm for v in vec]
    return vec


def main():
    print(f"Generating {NUM_PROBES} probe vectors of dimension {DIMS}...")
    probes = [generate_probe_vector(i) for i in range(NUM_PROBES)]

    # Write to header file
    out_path = "src/probe_vectors.h"
    with open(out_path, "w") as f:
        f.write("#pragma once\n")
        f.write("// AUTO-GENERATED by scripts/gen_probes.py — DO NOT EDIT MANUALLY\n")
        f.write("// Prototype-3 probe vectors: 32 x 384, Halton low-discrepancy sequence\n")
        f.write("// Used for segment routing: dot(query, probe[i]) > 0 sets bit i in segment_key\n\n")
        f.write(f"static constexpr int P3_NUM_PROBES = {NUM_PROBES};\n")
        f.write(f"static constexpr int P3_DIMS = {DIMS};\n\n")
        f.write(f"static const float PROBE_VECTORS[{NUM_PROBES}][{DIMS}] = {{\n")
        for i, vec in enumerate(probes):
            f.write(f"    {{ // probe {i}\n")
            vals_per_line = 8
            for j in range(0, DIMS, vals_per_line):
                chunk = vec[j:j + vals_per_line]
                line = ", ".join(f"{v:.8f}f" for v in chunk)
                f.write(f"        {line},\n")
            f.write("    },\n")
        f.write("};\n")

    print(f"Written: {out_path}")
    print(f"  {NUM_PROBES} probes × {DIMS} dims = {NUM_PROBES * DIMS} floats")

    # Quick sanity: check each vector is roughly unit norm
    for i, vec in enumerate(probes):
        norm = math.sqrt(sum(v * v for v in vec))
        if abs(norm - 1.0) > 0.01:
            print(f"  WARNING: probe {i} norm = {norm:.4f} (expected ~1.0)")

    print("Probe vector generation complete.")


if __name__ == "__main__":
    main()
